# Generated by Django 4.1 on 2023-01-18 08:29

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatset',
            name='conten',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
