# Generated by Django 4.1 on 2023-01-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_prettynum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prettynum',
            old_name='starus',
            new_name='status',
        ),
    ]
